### ISSUE TITLE
How can I find the locations that can be added to the settings.json?

### ISSUE THREAD

**Issue by sebamar88** [WebPageTest/wpt-vscode-extension#12]
Because here: "https://www.webpagetest.org/getLocations.php?f=html" they are with a different format and using it gives error.
For example, I need the location of Sao Paulo, Brazil. And I can't find how to use it

**Comment by Siddhantshukla814** [comment]
https://www.webpagetest.org/getLocations.php?f=json&k=a

This will give you a JSON object of all the available locations. All you have to do is use following format: location:browser.connectivity.

for example:
![image](https://user-images.githubusercontent.com/70441430/210396086-0b63da99-7b2e-4b77-b19b-ca363727fe77.png)
to use this specific location. Do this following change in for settings.json file.

`"WebPageTest.location": "ec2-us-east-1:Chrome.Cable"`
